In [1]:
from sklearn.preprocessing import FunctionTransformer

In [2]:
import numpy as np
import pandas as pd

In [5]:
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

# Transform all the values is log

In [7]:
b= FunctionTransformer(np.log1p)
b

FunctionTransformer(func=<ufunc 'log1p'>)

In [13]:
x_transfromed = b.transform(x)
x_transfromed

array([[0.69314718, 1.09861229],
       [1.38629436, 1.60943791]])

# Custom Feature Engineering

In [15]:
x= np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [27]:
def squ(x):
    return np.hstack((x, x**2))

In [28]:
custom_transformer = FunctionTransformer(squ)
custom_transformer

In [30]:
x_transformed = custom_transformer.transform(x)
x_transformed

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16]])

# create a matrix and and preform max divied of that

In [31]:
x = np.array([[1,2],[3,4]])

In [32]:
def mydivide(x):
    return x/np.max(x)

In [35]:
custom_transformer = FunctionTransformer(mydivide)

In [36]:
x_transformed = custom_transformer.transform(x)
x_transformed

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# Write a program who replace missing values to 0

In [38]:
x =np.array([[1,2,np.nan],[4,np.nan , 6]])x
x

array([[ 1.,  2., nan],
       [ 4., nan,  6.]])

In [39]:
def my_cleaning(x):
    x[np.isnan(x)] = 0
    return x

In [40]:
custom_transformer = FunctionTransformer(my_cleaning)

In [41]:
x_transformed = custom_transformer.transform(x)
x_transformed

array([[1., 2., 0.],
       [4., 0., 6.]])